// Owned by Wave 1 / Agent A (mock server).
// writeMockServer: emit a zero-dependency Node http server (+routes.json, seeds.json,
// package.json, README) that behaves like a real backend:
//  - best-match selects among same-path fixtures by query signature / request-body
//    hash / GraphQL operationName (falls back to the generic variant),
//  - maintains an in-memory store seeded from MockSeedEntity[] so GET list/detail
//    are served from the store and POST/PUT/PATCH/DELETE mutate it,
//  - replays SSE transcripts for isStream fixtures,
//  - permissive CORS + a POST /__seed reset.
import { mkdir, writeFile } from 'fs/promises';
import * as path from 'path';
import type { ApiFixture, MockRoute, MockSeedEntity } from '../types';
import {
  querySignature as querySignatureOf,
  requestBodyHash as requestBodyHashOf,
} from './fixtures';

/** The runnable ESM mock server (no deps beyond Node built-ins). */
const SERVER_MJS = String.raw`// Generated by screenshotter — zero-dependency STATEFUL mock API server.
// Serves recorded fixtures with request-aware best-match selection, an in-memory
// CRUD store seeded from seeds.json, and SSE replay — for local rebuilds.
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT) || 8787;

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS',
  'Access-Control-Allow-Headers': '*',
};

// ── canon + hash (mirrors src/api/fixtures.ts so matching is identical) ──
function canon(v) {
  if (v === null || v === undefined) return 'null';
  if (typeof v !== 'object') return JSON.stringify(v);
  if (Array.isArray(v)) return '[' + v.map(canon).join(',') + ']';
  const keys = Object.keys(v).sort();
  return '{' + keys.map((k) => JSON.stringify(k) + ':' + canon(v[k])).join(',') + '}';
}
function stableHash(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;
  }
  return ('00000000' + h.toString(16)).slice(-8);
}
const VOLATILE_QUERY_RE = /^(_$|_t$|ts$|t$|cb$|v$|timestamp|nonce|sig|signature|rand)/i;
function querySignature(params) {
  const parts = [];
  const keys = [...new Set([...params.keys()])].sort();
  for (const key of keys) {
    if (VOLATILE_QUERY_RE.test(key)) continue;
    const vs = params.getAll(key).map(String).sort();
    parts.push(key + '=' + vs.join(','));
  }
  return parts.join('&');
}
function bodyHash(body) {
  if (body === undefined || body === null) return '';
  return stableHash(canon(body));
}
function gqlOperation(body) {
  if (body && typeof body === 'object' && !Array.isArray(body)) {
    if (typeof body.operationName === 'string' && body.operationName) return body.operationName;
    if (typeof body.query === 'string') {
      const m = body.query.match(/\b(query|mutation|subscription)\s+([A-Za-z0-9_]+)/);
      if (m) return m[2];
    }
  }
  return undefined;
}

function escapeRe(s) {
  return s.replace(/[.*+?^\${}()|[\]\\]/g, '\\$&');
}
// Compile "/a/{id}/b" to a RegExp capturing each {param}.
function compile(template) {
  const names = [];
  const pattern = template
    .split('/')
    .map((seg) => {
      const m = /^\{([^}]+)\}$/.exec(seg);
      if (m) { names.push(m[1]); return '([^/]+)'; }
      return escapeRe(seg);
    })
    .join('/');
  return { re: new RegExp('^' + pattern + '$'), names };
}

const routesRaw = await readFile(join(here, 'routes.json'), 'utf8');
const ROUTES = JSON.parse(routesRaw).map((r) => ({ ...r, ...compile(r.pathTemplate) }));

let SEEDS = [];
try {
  SEEDS = JSON.parse(await readFile(join(here, 'seeds.json'), 'utf8'));
} catch { SEEDS = []; }

// ── In-memory stateful store: resource -> Map<id, record> ──
const store = new Map();
function idOf(rec, fallback) {
  if (rec && typeof rec === 'object') {
    for (const k of ['id', '_id', 'slug', 'name', 'key', 'uuid']) {
      if (rec[k] !== undefined && rec[k] !== null) return String(rec[k]);
    }
  }
  return String(fallback);
}
function seedStore() {
  store.clear();
  let auto = 1;
  for (const s of SEEDS) {
    if (!s || typeof s !== 'object' || !s.resource) continue;
    let coll = store.get(s.resource);
    if (!coll) { coll = new Map(); store.set(s.resource, coll); }
    const id = s.id != null ? String(s.id) : idOf(s.data, auto++);
    coll.set(id, s.data);
  }
}
seedStore();

const fixtureCache = new Map();
async function loadFixture(bodyFile) {
  if (fixtureCache.has(bodyFile)) return fixtureCache.get(bodyFile);
  const parsed = JSON.parse(await readFile(join(here, bodyFile), 'utf8'));
  fixtureCache.set(bodyFile, parsed);
  return parsed;
}
function unwrap(parsed) {
  return parsed && typeof parsed === 'object' && 'response' in parsed ? parsed.response : parsed;
}

async function readBody(req) {
  const chunks = [];
  let size = 0;
  for await (const c of req) {
    size += c.length;
    if (size > 8 * 1024 * 1024) break; // 8MB cap
    chunks.push(c);
  }
  const raw = Buffer.concat(chunks).toString('utf8');
  if (!raw) return undefined;
  try { return JSON.parse(raw); } catch { return raw; }
}

// Score a candidate route against the request (higher = better match).
function scoreRoute(route, qsig, bHash, op) {
  // SOFT matching: prefer exact query/body/operation matches, but never hard-reject
  // the only same-method+path fixture — a non-captured query or a NEW POST body must
  // still fall back to a recorded fixture (and, for writes, hit the stateful store)
  // rather than 404. GraphQL operation is the strongest signal but still soft.
  let score = 1; // method+path already matched
  if (route.matchOperation) {
    if (route.matchOperation === op) score += 100;
  }
  if (route.matchBodyHash) {
    if (route.matchBodyHash === bHash) score += 50;
  }
  if (route.matchQuery) {
    const want = querySignatureFromObj(route.matchQuery);
    if (want === qsig) score += 25;
    else if (want && qsig && qsig.includes(want)) score += 5;
  } else if (!qsig) {
    score += 2; // generic route preferred for a no-query request
  }
  return score;
}
function querySignatureFromObj(obj) {
  const p = new URLSearchParams();
  for (const [k, v] of Object.entries(obj)) {
    if (Array.isArray(v)) v.forEach((x) => p.append(k, String(x)));
    else p.append(k, String(v));
  }
  return querySignature(p);
}

function pickRoute(method, pathname, qsig, bHash, op) {
  let best = null;
  let bestScore = -1;
  for (const r of ROUTES) {
    if (r.method.toUpperCase() !== method) continue;
    if (!r.re.test(pathname)) continue;
    const s = scoreRoute(r, qsig, bHash, op);
    if (s > bestScore) { bestScore = s; best = r; }
  }
  return best;
}

function send(res, status, headers, body) {
  res.writeHead(status, { ...CORS, ...headers });
  res.end(typeof body === 'string' ? body : JSON.stringify(body));
}

// SSE replay: write each transcript frame as an event, then close.
async function streamSSE(res, frames, extraHeaders) {
  res.writeHead(200, {
    ...CORS,
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    ...extraHeaders,
  });
  for (const frame of frames) {
    const text = typeof frame === 'string' ? frame : JSON.stringify(frame);
    // If the captured frame already looks like an SSE line, pass it through.
    if (/^(data|event|id|retry):/m.test(text)) res.write(text.endsWith('\n') ? text : text + '\n\n');
    else res.write('data: ' + text.replace(/\n/g, '\\n') + '\n\n');
  }
  res.write('data: [DONE]\n\n');
  res.end();
}

const server = createServer(async (req, res) => {
  const method = (req.method || 'GET').toUpperCase();
  if (method === 'OPTIONS') { res.writeHead(204, CORS); res.end(); return; }

  let url;
  try { url = new URL(req.url || '/', 'http://localhost'); }
  catch { return send(res, 400, { 'Content-Type': 'application/json' }, { error: 'bad url' }); }
  const pathname = url.pathname;

  // Reset endpoint: re-seed the store.
  if (method === 'POST' && pathname === '/__seed') {
    seedStore();
    return send(res, 200, { 'Content-Type': 'application/json' }, { ok: true, reseeded: SEEDS.length });
  }

  const reqBody = method === 'GET' || method === 'HEAD' ? undefined : await readBody(req);
  const qsig = querySignature(url.searchParams);
  const op = gqlOperation(reqBody);
  const bHash = op ? '' : bodyHash(reqBody);

  const route = pickRoute(method, pathname, qsig, bHash, op);
  if (!route) {
    return send(res, 404, { 'Content-Type': 'application/json' }, { error: 'no fixture', method, path: pathname });
  }

  const headers = { 'Content-Type': route.contentType || 'application/json', ...(route.responseHeaders || {}) };

  // ── Streaming replay ──
  if (route.isStream) {
    try {
      const parsed = await loadFixture(route.bodyFile);
      const frames = Array.isArray(parsed && parsed.streamTranscript) ? parsed.streamTranscript : [];
      if (frames.length > 0) return streamSSE(res, frames, route.responseHeaders || {});
    } catch { /* fall through to plain body */ }
  }

  // ── Stateful CRUD against the store ──
  if (route.resource && route.crud) {
    const coll = store.get(route.resource) || (store.set(route.resource, new Map()), store.get(route.resource));
    const segs = pathname.split('/').filter(Boolean);
    const lastId = decodeURIComponent(segs[segs.length - 1] || '');
    try {
      // Lazily hydrate the collection from the recorded fixture body the first
      // time it's read, so the store is never empty even without explicit seeds.
      if ((route.crud === 'list' || route.crud === 'get') && coll.size === 0) {
        await hydrateFromFixture(route, coll);
      }
      if (route.crud === 'list') {
        const items = [...coll.values()];
        // Echo the recorded envelope shape when the fixture wraps the list.
        const tmpl = unwrap(await loadFixture(route.bodyFile));
        return send(res, route.status || 200, headers, reshapeList(tmpl, items));
      }
      if (route.crud === 'get') {
        let rec = coll.get(lastId);
        if (rec === undefined && coll.size === 1) rec = [...coll.values()][0];
        if (rec === undefined) {
          // Fall back to the recorded detail body verbatim.
          const tmpl = unwrap(await loadFixture(route.bodyFile));
          if (tmpl !== undefined) return send(res, route.status || 200, headers, tmpl);
          return send(res, 404, headers, { error: 'not found', id: lastId });
        }
        return send(res, route.status || 200, headers, rec);
      }
      if (route.crud === 'create') {
        const rec = reqBody && typeof reqBody === 'object' ? { ...reqBody } : { value: reqBody };
        const id = idOf(rec, Date.now());
        if (rec && typeof rec === 'object' && rec.id === undefined) rec.id = id;
        coll.set(id, rec);
        return send(res, route.status && route.status >= 200 ? route.status : 201, headers, rec);
      }
      if (route.crud === 'update') {
        const prev = coll.get(lastId) || {};
        const next = method === 'PUT'
          ? (reqBody && typeof reqBody === 'object' ? reqBody : prev)
          : { ...prev, ...(reqBody && typeof reqBody === 'object' ? reqBody : {}) };
        coll.set(lastId, next);
        return send(res, route.status || 200, headers, next);
      }
      if (route.crud === 'delete') {
        coll.delete(lastId);
        return send(res, route.status || 204, headers, route.status === 200 ? { ok: true } : '');
      }
    } catch (err) {
      return send(res, 500, headers, { error: 'store error', detail: String(err) });
    }
  }

  // ── Plain fixture replay (echo a plausible body for writes) ──
  try {
    const parsed = await loadFixture(route.bodyFile);
    let body = unwrap(parsed);
    // For a non-GraphQL write whose recorded body is a plain object, echo the
    // request merged onto the recorded shape so the UI sees its own input.
    // GraphQL responses (matchOperation) are returned verbatim — merging the
    // {operationName, query, variables} envelope in would corrupt them.
    if (
      method !== 'GET' &&
      method !== 'HEAD' &&
      !route.matchOperation &&
      reqBody &&
      typeof reqBody === 'object'
    ) {
      if (body && typeof body === 'object' && !Array.isArray(body)) body = { ...body, ...reqBody };
    }
    return send(res, route.status || 200, headers, body);
  } catch (err) {
    return send(res, 500, headers, { error: 'fixture read failed', detail: String(err) });
  }
});

// Hydrate a store collection from a fixture body's array (envelope-aware), so a
// list/detail GET returns recorded data even when no explicit seeds were given.
async function hydrateFromFixture(route, coll) {
  const tmpl = unwrap(await loadFixture(route.bodyFile));
  const arr = extractArray(tmpl);
  if (arr) {
    let auto = 1;
    for (const rec of arr) coll.set(idOf(rec, auto++), rec);
  } else if (tmpl && typeof tmpl === 'object') {
    // A single detail object → store under its derived id.
    coll.set(idOf(tmpl, 1), tmpl);
  }
}

// Find the row array inside a recorded list body (top-level or common envelope).
function extractArray(tmpl) {
  if (Array.isArray(tmpl)) return tmpl;
  if (tmpl && typeof tmpl === 'object') {
    for (const k of ['data', 'items', 'results', 'rows', 'records', 'nodes']) {
      if (Array.isArray(tmpl[k])) return tmpl[k];
    }
  }
  return null;
}

// Reshape a list response to the recorded envelope (e.g. { data: [...] }).
function reshapeList(tmpl, items) {
  if (Array.isArray(tmpl)) return items;
  if (tmpl && typeof tmpl === 'object') {
    for (const k of ['data', 'items', 'results', 'rows', 'records', 'edges', 'nodes']) {
      if (Array.isArray(tmpl[k])) return { ...tmpl, [k]: items };
    }
  }
  return items;
}

server.listen(PORT, () => {
  process.stderr.write(
    'stateful mock API on http://localhost:' + PORT + ' (' + ROUTES.length + ' routes, ' + SEEDS.length + ' seeds)\n',
  );
});
`;

/** Build the one-screen README. */
function readme(routeCount: number, seedCount: number): string {
  return `# screenshotter mock API (stateful)

Zero-dependency mock of the captured API. It behaves like a real backend so a
local rebuild can talk to a working server offline:

- **Request-aware**: same-path fixtures are disambiguated by query signature,
  request-body hash, or GraphQL \`operationName\` (best match wins; falls back to
  the generic variant).
- **Stateful**: an in-memory store is seeded from \`seeds.json\` (${seedCount} seed
  record${seedCount === 1 ? '' : 's'}). \`GET\` list/detail read from it;
  \`POST/PUT/PATCH/DELETE\` mutate it and echo a plausible body.
- **Streaming**: \`isStream\` fixtures replay their captured transcript as SSE
  (\`text/event-stream\`).

## Run

\`\`\`sh
node server.mjs
# or
npm start
\`\`\`

Base URL: \`http://localhost:8787\` (override with \`PORT=9000 node server.mjs\`).

Reset the store to its seeds at any time:

\`\`\`sh
curl -X POST http://localhost:8787/__seed
\`\`\`

It serves ${routeCount} recorded route${routeCount === 1 ? '' : 's'} from
\`routes.json\` (bodies in \`../fixtures/\`) with permissive CORS
(\`Access-Control-Allow-Origin: *\`). Unmatched requests return
\`404 { "error": "no fixture" }\`.
`;
}

/**
 * Infer the CRUD role + resource for a fixture, so the stateful store can serve
 * it. A GET on a collection path ("/api/models") is a `list`; a GET on a
 * detail path ("/api/models/{id}") is a `get`; POST=create, PUT/PATCH=update,
 * DELETE=delete on the matching resource. Resource = last static segment.
 */
function deriveCrud(f: ApiFixture): { resource?: string; crud?: MockRoute['crud'] } {
  const segs = f.pathTemplate.split('/').filter((s) => s.length > 0);
  if (segs.length === 0) return {};
  const endsWithParam = /^\{[^}]+\}$/.test(segs[segs.length - 1]);
  // Resource name = last NON-param segment.
  let resource: string | undefined;
  for (let i = segs.length - 1; i >= 0; i--) {
    if (!/^\{[^}]+\}$/.test(segs[i])) { resource = segs[i]; break; }
  }
  if (!resource) return {};
  // GraphQL / streaming endpoints are not REST resources.
  if (f.graphqlOperation || f.isStream) return {};

  const method = f.method.toUpperCase();
  if (method === 'GET') return { resource, crud: endsWithParam ? 'get' : 'list' };
  if (method === 'POST' && !endsWithParam) return { resource, crud: 'create' };
  if ((method === 'PUT' || method === 'PATCH') && endsWithParam) return { resource, crud: 'update' };
  if (method === 'DELETE' && endsWithParam) return { resource, crud: 'delete' };
  return {};
}

/** Re-derive the matchQuery object from a fixture's query signature. */
function matchQueryOf(f: ApiFixture): Record<string, string> | undefined {
  if (!f.querySignature) return undefined;
  const out: Record<string, string> = {};
  for (const part of f.querySignature.split('&')) {
    const eq = part.indexOf('=');
    if (eq === -1) continue;
    out[part.slice(0, eq)] = part.slice(eq + 1);
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

/** Map fixtures → MockRoutes (request-aware + stateful + streaming metadata). */
export function fixturesToRoutes(fixtures: ApiFixture[]): MockRoute[] {
  return fixtures.map((f) => {
    const { resource, crud } = deriveCrud(f);
    const route: MockRoute = {
      method: f.method,
      pathTemplate: f.pathTemplate,
      status: f.status,
      contentType: f.contentType,
      bodyFile: `../fixtures/${f.file}`,
    };
    const mq = matchQueryOf(f);
    if (mq) route.matchQuery = mq;
    if (f.requestBodyHash) route.matchBodyHash = f.requestBodyHash;
    if (f.graphqlOperation) route.matchOperation = f.graphqlOperation;
    if (f.responseHeaders) route.responseHeaders = f.responseHeaders;
    if (f.isStream) route.isStream = true;
    if (resource) route.resource = resource;
    if (crud) route.crud = crud;
    return route;
  });
}

export async function writeMockServer(
  fixtures: ApiFixture[],
  mockDir: string,
  seeds: MockSeedEntity[] = [],
): Promise<void> {
  await mkdir(mockDir, { recursive: true });

  const routes = fixturesToRoutes(fixtures);

  const pkg = {
    name: 'screenshotter-mock',
    private: true,
    type: 'module',
    scripts: { start: 'node server.mjs' },
  };

  await Promise.all([
    writeFile(path.join(mockDir, 'routes.json'), JSON.stringify(routes, null, 2), 'utf8'),
    writeFile(path.join(mockDir, 'seeds.json'), JSON.stringify(seeds, null, 2), 'utf8'),
    writeFile(path.join(mockDir, 'server.mjs'), SERVER_MJS, 'utf8'),
    writeFile(path.join(mockDir, 'package.json'), JSON.stringify(pkg, null, 2), 'utf8'),
    writeFile(path.join(mockDir, 'README.md'), readme(routes.length, seeds.length), 'utf8'),
  ]);
}

// Re-exported so the orchestrator can build seeds with the same signature helpers.
export { querySignatureOf, requestBodyHashOf };
